### ISSUE TITLE
'tx_staticinfotables_domain_model_language' doesn't exist

### ISSUE THREAD

**Issue by loco8878** [TYPO3-extensions/static_info_tables#1]
![fullexception](https://cloud.githubusercontent.com/assets/7300248/11064662/e24089f8-87be-11e5-881a-a53e5429d679.png)
This error occurs on the root page ln list view: 

An error occurred trying to process items for field "Select Official Language (ISO code):" (Table 'tx_staticinfotables_domain_model_language' doesn't exist).

System:
TYPO3 6.2.15
static_info_tables 6.3.1

https://wiki.typo3.org/Exception/CMS/1247602160#.27tx_staticinfotables_domain_model_language.27_doesn.27t_exist

**Comment by vergissberlin** [comment]
Ping!

**Comment by PowerKiKi** [comment]
Nobody is active on this repository. Your best bet is to track the latest extension contributor and ping him directly

**Comment by friend8** [comment]
Hi @sjbrca,

can you tell us something according this error?

**Comment by sjbrca** [comment]
You should upgrade to the latest version which is 6.3.9.

https://typo3.org/extensions/repository/view/static_info_tables

**Comment by friend8** [comment]
Hi @sjbrca,
I've updated to 6.3.9 and the error still remains.
This seems like a table name dynamically created by Typo3.

**Comment by PeterTheOne** [comment]
@friend8 Do you know if this has been fixed in the mean time? https://forge.typo3.org/issues/77144 is still open..

**Comment by friend8** [comment]
Hi @PeterTheOne,
as far as I know, this hasn't been fixed.
